services:
   accounts:
      image: "biswa18/accounts:s4"
      container_name: accounts-ms
      ports:
        - "8080:8080"
      deploy:
         resources:
            limits:
               memory: 700m
      networks:
       - biswa18
   loans:
      image: "biswa18/loans:s4"
      container_name: loans-ms
      ports:
        - "8090:8090"
      deploy:
         resources:
            limits:
               memory: 700m
      networks:
       - biswa18
   cards:
      image: "biswa18/cards:s4"
      container_name: cards-ms
      ports:
        - "9000:9000"
      deploy:
         resources:
            limits:
               memory: 700m
      networks:
       - biswa18     
networks:
    biswa18:
       driver: "bridge"  